
class CryoEMConfig:
    # max ctf number allowed
    REGRESSION = 0
    CLASSIFICATION = 1
    TRAIN = 0
    VALIDATION = 1
    MAX_CTF_VALUE = 20.0
    LOW_CTF_THRESH = 6.0
    MAX_HOLE_CNT_PER_PATCH = 25.0
    MAX_HOLE_CNT_PER_SQUARE= 150.0
    MAX_HOLE_CNT_PER_GRID = 500.0
    FEATURE_DIM = 17 #20 #13 #23 #16
    HISTORY_SIZE = 4
    FEATURE_HISTOGRAM_BIN = [0, 4, 6, 8, 10, 999999]
    #FEATURE_HISTOGRAM_BIN = [0, 6, 10, 999999]
    GAUSS_FILTER_SIZE = 0.0

#    SWITCH_GRID_LOSS = 15
#    SWITCH_SQUARE_LOSS = 10
#    SWITCH_PATCH_LOSS = 5
#    SWITCH_HOLE_LOSS = 2
    SWITCH_GRID_LOSS = 8
    SWITCH_SQUARE_LOSS = 6
    SWITCH_PATCH_LOSS = 2
    SWITCH_HOLE_LOSS = 1

    Searching_Limit = 120
    LOW_CTF_REWARD = 1
    HIGH_CTF_REWARD = 0
